using SDL2;

namespace Worms.engine.core.input.listener; 

public static class ScanCodeToButton {
    public static readonly Dictionary<SDL.SDL_Scancode, Button> SCANCODE_TO_BUTTON = new() {
        { SDL.SDL_Scancode.SDL_SCANCODE_SPACE, Button.SPACE },
        { SDL.SDL_Scancode.SDL_SCANCODE_KP_SPACE, Button.SPACE },
        { SDL.SDL_Scancode.SDL_SCANCODE_LCTRL, Button.CTRL },
        { SDL.SDL_Scancode.SDL_SCANCODE_RCTRL, Button.CTRL },
        { SDL.SDL_Scancode.SDL_SCANCODE_LSHIFT, Button.SHIFT },
        { SDL.SDL_Scancode.SDL_SCANCODE_RSHIFT, Button.SHIFT },
        { SDL.SDL_Scancode.SDL_SCANCODE_CAPSLOCK, Button.CAPS_LOCK },
        { SDL.SDL_Scancode.SDL_SCANCODE_TAB, Button.TAB },
        { SDL.SDL_Scancode.SDL_SCANCODE_KP_TAB, Button.TAB },
        { SDL.SDL_Scancode.SDL_SCANCODE_LALT, Button.ALT },
        { SDL.SDL_Scancode.SDL_SCANCODE_RALT, Button.ALT },
        { SDL.SDL_Scancode.SDL_SCANCODE_KP_ENTER, Button.ENTER },
        { SDL.SDL_Scancode.SDL_SCANCODE_BACKSPACE, Button.BACKSPACE },
        { SDL.SDL_Scancode.SDL_SCANCODE_KP_BACKSPACE, Button.BACKSPACE },
        { SDL.SDL_Scancode.SDL_SCANCODE_ESCAPE, Button.ESCAPE },
        { SDL.SDL_Scancode.SDL_SCANCODE_LEFT, Button.LEFT },
        { SDL.SDL_Scancode.SDL_SCANCODE_RIGHT, Button.RIGHT },
        { SDL.SDL_Scancode.SDL_SCANCODE_UP, Button.UP },
        { SDL.SDL_Scancode.SDL_SCANCODE_DOWN, Button.DOWN },
        { SDL.SDL_Scancode.SDL_SCANCODE_1, Button.NUM_1 },
        { SDL.SDL_Scancode.SDL_SCANCODE_2, Button.NUM_2 },
        { SDL.SDL_Scancode.SDL_SCANCODE_3, Button.NUM_3 },
        { SDL.SDL_Scancode.SDL_SCANCODE_4, Button.NUM_4 },
        { SDL.SDL_Scancode.SDL_SCANCODE_5, Button.NUM_5 },
        { SDL.SDL_Scancode.SDL_SCANCODE_6, Button.NUM_6 },
        { SDL.SDL_Scancode.SDL_SCANCODE_7, Button.NUM_7 },
        { SDL.SDL_Scancode.SDL_SCANCODE_8, Button.NUM_8 },
        { SDL.SDL_Scancode.SDL_SCANCODE_9, Button.NUM_9 },
        { SDL.SDL_Scancode.SDL_SCANCODE_0, Button.NUM_0 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F1, Button.F1 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F2, Button.F2 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F3, Button.F3 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F4, Button.F4 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F5, Button.F5 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F6, Button.F6 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F7, Button.F7 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F8, Button.F8 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F9, Button.F9 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F10, Button.F10 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F11, Button.F11 },
        { SDL.SDL_Scancode.SDL_SCANCODE_F12, Button.F12 },
        { SDL.SDL_Scancode.SDL_SCANCODE_A, Button.A },
        { SDL.SDL_Scancode.SDL_SCANCODE_B, Button.B },
        { SDL.SDL_Scancode.SDL_SCANCODE_C, Button.C },
        { SDL.SDL_Scancode.SDL_SCANCODE_D, Button.D },
        { SDL.SDL_Scancode.SDL_SCANCODE_E, Button.E },
        { SDL.SDL_Scancode.SDL_SCANCODE_F, Button.F },
        { SDL.SDL_Scancode.SDL_SCANCODE_G, Button.G },
        { SDL.SDL_Scancode.SDL_SCANCODE_H, Button.H },
        { SDL.SDL_Scancode.SDL_SCANCODE_I, Button.I },
        { SDL.SDL_Scancode.SDL_SCANCODE_J, Button.J },
        { SDL.SDL_Scancode.SDL_SCANCODE_K, Button.K },
        { SDL.SDL_Scancode.SDL_SCANCODE_L, Button.L },
        { SDL.SDL_Scancode.SDL_SCANCODE_M, Button.M },
        { SDL.SDL_Scancode.SDL_SCANCODE_N, Button.N },
        { SDL.SDL_Scancode.SDL_SCANCODE_O, Button.O },
        { SDL.SDL_Scancode.SDL_SCANCODE_P, Button.P },
        { SDL.SDL_Scancode.SDL_SCANCODE_Q, Button.Q },
        { SDL.SDL_Scancode.SDL_SCANCODE_R, Button.R },
        { SDL.SDL_Scancode.SDL_SCANCODE_S, Button.S },
        { SDL.SDL_Scancode.SDL_SCANCODE_T, Button.T },
        { SDL.SDL_Scancode.SDL_SCANCODE_U, Button.U },
        { SDL.SDL_Scancode.SDL_SCANCODE_V, Button.V },
        { SDL.SDL_Scancode.SDL_SCANCODE_W, Button.W },
        { SDL.SDL_Scancode.SDL_SCANCODE_X, Button.X },
        { SDL.SDL_Scancode.SDL_SCANCODE_Y, Button.Y },
        { SDL.SDL_Scancode.SDL_SCANCODE_Z, Button.Z },
    };
    
    public static readonly Dictionary<Button, HashSet<SDL.SDL_Scancode>> BUTTON_TO_SCANCODE = new() {
        { Button.SPACE, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_SPACE, SDL.SDL_Scancode.SDL_SCANCODE_KP_SPACE } },
        { Button.CTRL, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_LCTRL, SDL.SDL_Scancode.SDL_SCANCODE_RCTRL } },
        { Button.SHIFT, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_LSHIFT, SDL.SDL_Scancode.SDL_SCANCODE_RSHIFT } },
        { Button.CAPS_LOCK, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_CAPSLOCK } },
        { Button.TAB, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_TAB, SDL.SDL_Scancode.SDL_SCANCODE_KP_TAB } },
        { Button.ALT, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_LALT, SDL.SDL_Scancode.SDL_SCANCODE_RALT } },
        { Button.ENTER, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_KP_ENTER } },
        { Button.BACKSPACE, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_BACKSPACE, SDL.SDL_Scancode.SDL_SCANCODE_KP_BACKSPACE } },
        { Button.ESCAPE, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_ESCAPE } },
        { Button.LEFT, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_LEFT } },
        { Button.RIGHT, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_RIGHT } },
        { Button.UP, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_UP } },
        { Button.DOWN, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_DOWN } },
        { Button.NUM_1, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_1 } },
        { Button.NUM_2, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_2 } },
        { Button.NUM_3, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_3 } },
        { Button.NUM_4, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_4 } },
        { Button.NUM_5, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_5 } },
        { Button.NUM_6, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_6 } },
        { Button.NUM_7, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_7 } },
        { Button.NUM_8, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_8 } },
        { Button.NUM_9, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_9 } },
        { Button.NUM_0, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_0 } },
        { Button.F1, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F1 } },
        { Button.F2, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F2 } },
        { Button.F3, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F3 } },
        { Button.F4, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F4 } },
        { Button.F5, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F5 } },
        { Button.F6, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F6 } },
        { Button.F7, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F7 } },
        { Button.F8, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F8 } },
        { Button.F9, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F9 } },
        { Button.F10, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F10 } },
        { Button.F11, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F11 } },
        { Button.F12, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F12 } },
        { Button.A, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_A } },
        { Button.B, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_B } },
        { Button.C, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_C } },
        { Button.D, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_D } },
        { Button.E, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_E } },
        { Button.F, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_F } },
        { Button.G, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_G } },
        { Button.H, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_H } },
        { Button.I, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_I } },
        { Button.J, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_J } },
        { Button.K, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_K } },
        { Button.L, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_L } },
        { Button.M, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_M } },
        { Button.N, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_N } },
        { Button.O, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_O } },
        { Button.P, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_P } },
        { Button.Q, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_Q } },
        { Button.R, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_R } },
        { Button.S, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_S } },
        { Button.T, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_T } },
        { Button.U, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_U } },
        { Button.V, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_V } },
        { Button.W, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_W } },
        { Button.X, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_X } },
        { Button.Y, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_Y } },
        { Button.Z, new HashSet<SDL.SDL_Scancode> { SDL.SDL_Scancode.SDL_SCANCODE_Z } },
    };
}